version: '3.8'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./back
    ports:
      - "3001:3001"
